py/desisurvey/nextfield.py
This is a first pass at a preliminary next field selector. So far, it calculates the local apparent sidereal time at the scope, then uses that information to determine what fields are above the horizon, and selects a field with a low declination that is also within an hour of the meridian. It is currently using PyAstronomy to find out if the Sun is up, determine the location of the Moon and find the Moon's phase. I will be exploring other packages that can do this, as well as trying to replace some calculations with calls to astropy where possible.
=> Nextfield prelim

py/desisurvey/nextfield.py
I have removed the dependence on PyAstronomy completely, with pyephem now doing the calculation of the Moon's attributes for the date of observation. All unit tests still pass. Currently the next field selector only calculates the Moon's attributes but does not use them for anything.
=> Addpyephem

py/desisurvey/avoidobject.py, py/desisurvey/test/test_avoidobject.py
I added the avoidobject routine from Martin's package and used astropy instead of pyephem
=> Refactored surveysim

py/desisurvey/nextobservation.py
Changed definition from
moonfrac < 0.2 or (moonalt x moonfrac < 12.0)
to
moonfrac < 0.6 and (moonalt x moonfrac < 30.0)
to reflect canonical definition cited in FDR.
This PR fixes #13
=> Changed definition of grey time

py/desisurvey/test/test_utils.py, py/desisurvey/utils.py
=> Fixed bug in equatorial to galactic coordinate transform.

doc/changes.rst, py/desisurvey/plan.py, py/desisurvey/plots.py, py/desisurvey/test/test_plan.py, py/desisurvey/utils.py
This is still work in progress but merging now so @mlandriau can work on afternoonplan and nextobservation.
=> Implement greedy scheduler

doc/changes.rst, py/desisurvey/test/__init__.py, py/desisurvey/test/desisurvey_test_suite.py, py/desisurvey/test/test_avoidobject.py, py/desisurvey/test/test_config.py, py/desisurvey/test/test_ephemerides.py, py/desisurvey/test/test_etc.py, py/desisurvey/test/test_nextfield.py, py/desisurvey/test/test_progress.py, py/desisurvey/test/test_schedule.py, py/desisurvey/test/test_surveyplan.py, py/desisurvey/test/test_utils.py
This PR fixes the test suite so that `python setup.py test` works.  There are other problems with the unit tests.  @dkirkby, @sbailey, let's use the discussion of the PR to debug the remaining issues.
=> Fix test suite

doc/changes.rst, py/desisurvey/progress.py
Adds a 'FLAVOR' column to the output of `desisurvey.progress.Progress.get_exposures()`.
=> Add flavor column

.travis.yml, doc/changes.rst, py/desisurvey/progress.py
Trivial hack to address the immediate need (for the SV data challenge) documented by #85 but we may want a more thoughtful solution.
=> enforce at least six characters in program name

.travis.yml, py/desisurvey/tileqa.py
tileqa.qa() shows how to generate the new tiling pattern and demonstrates using the rest of the code to make QA plots.
This code had a number of dependences on routines that are in my usual library.  I've copied them into this bit of code to make it stand-alone, but presumably some subset of the match2d, lb2uv, lb2tp, tp2uv, match_radec, gc_dist, and subslices routines have more typical DESI equivalents that don't need to be replicated here.
=> DESI tiling dither pattern and QA code

py/desisurvey/rules.py, py/desisurvey/scheduler.py
This is a cosmetic PR to work about python 3.8 complaining about invalid escape sequences in regular expression and latex in docstrings.
=> fix py3.8 invalid escape sequences

py/desisurvey/NTS.py, py/desisurvey/data/config-cmx.yaml, py/desisurvey/scripts/run_plan.py
Adds req_efftime, sbprof fields to NTS return value for use by ETC.
=> Add additional info to NTS to enable ETC integration.

doc/changes.rst, py/desisurvey/NTS.py, py/desisurvey/config.py, py/desisurvey/data/config.yaml, py/desisurvey/ephem.py, py/desisurvey/etc.py, py/desisurvey/forecast.py, py/desisurvey/optimize.py, py/desisurvey/plan.py, py/desisurvey/rules.py, py/desisurvey/scheduler.py, py/desisurvey/scripts/afternoon_plan.py, py/desisurvey/scripts/collect_etc.py, py/desisurvey/scripts/run_plan.py, py/desisurvey/scripts/surveyinit.py, py/desisurvey/svstats.py, py/desisurvey/test/base.py, py/desisurvey/test/test_etc.py, py/desisurvey/test/test_plan.py, py/desisurvey/test/test_scheduler.py, py/desisurvey/tileqa.py, py/desisurvey/tiles.py, py/desisurvey/utils.py
This update primarily changes the config, tiles, and exposures file to match
https://desi.lbl.gov/trac/wiki/SurveyOps/DailyOps
Changes to the config and state touch all of the places in desisurvey that use them.  All information except for the ephemerides is now carried in the tiles file, instead of separate tiles/plan/scheduler/surveyinit files.
=> desisurvey/NTS updates for SV1

py/desisurvey/holdingpen.py, py/desisurvey/scheduler.py
Add routines to identify and remove stale fiberassign files, commit observed fiberassign files to SVN, and remove unobserved files from the SVN directory.
=> Add holding pen maintenance routines

doc/changes.rst, py/desisurvey/NTS.py, py/desisurvey/holdingpen.py, py/desisurvey/rules.py, py/desisurvey/scheduler.py, py/desisurvey/scripts/afternoon_plan.py, py/desisurvey/scripts/collect_etc.py, py/desisurvey/scripts/run_plan.py, py/desisurvey/utils.py
Miscellaneous holding pen and tile selection improvements.
=> NTS and holding pen updates

bin/fba-main-onthefly.sh, bin/fba-main.sh, doc/changes.rst, py/desisurvey/NTS.py, py/desisurvey/holdingpen.py, py/desisurvey/plan.py, py/desisurvey/scripts/afternoon_plan.py
This PR lets the NTS create fiberassign files on the fly.  This is controlled by the config variable fa_on_the_fly in afternoon planning.
=> Add fiberassign-on-the-fly capability.

bin/afternoon_plan, doc/changes.rst, py/desisurvey/forecast.py, py/desisurvey/scripts/collect_etc.py, py/desisurvey/scripts/run_plan.py, py/desisurvey/tileqa.py
This PR improves the logging during holding pen construction and more compulsively checks that the permissions are correct following construction.
=> Improve logging of holding pen construction & check permissions

doc/changes.rst, py/desisurvey/NTS.py, py/desisurvey/etc.py, py/desisurvey/scripts/surveyinit.py
A bit of miscellanea:
- Force permissions on newly created tile directories.
- Keep old design hour angles of observed tiles when updating hour angles.
- Change default airmass/cost power to 1.75.
=> Improve permissions on newly created tile directories

setup.py
This PR removes `desiutil.setup.DesiTest` from setup.py.
=> Remove DesiTest from setup.py

.github/workflows/python-package.yml, .gitignore, doc/conf.py, doc/rtd-requirements.txt
This PR updates the documentation configuration as prompted by desihub/desispec#2445.
=> Update doc configuration

py/desisurvey/NTS.py, py/desisurvey/scheduler.py
Be more careful about not crashing due to trying to os.chmod and not having the right permissions.
=> Add checks around os.chmod.

py/desisurvey/data/config.yaml
Increase tile radius from 1.62 deg to 1.63 deg.
=> Increase tile radius

bin/fba-main-onthefly.sh
@geordie666 , does this look right to you wrt the new desitarget / bright1b changes?  @araichoor , you know best but are traveling.  @sybenzvi , have we installed this on the desi cluster at KPNO?
=> Change bright1b program to use 3.2.0 targets

bin/fba-main-onthefly.sh, doc/changes.rst
=> Use desitarget/3.5.0 for fiber assignment.
