- py/desisurvey/nextfield.py
- py/desisurvey/test/test_nextfield.py
Added a test to make sure changes don't affect the answer given by get_next_field. Added removal of tiles with IDs listed in previoustiles. Fixed an omission in the get_next_field call in the test_previoustiles. All tests now pass.
> Unittest rightanswer

- doc/changes.rst
- py/desisurvey/nightcal.py
- py/desisurvey/test/test_nightcal.py
This PR fixes an off-by-one bug in the YEARMMDD vs. MJD of the sunset, originally discovered with code like this:
```python
from desisurvey.nightcal import getCalAll
from astropy.time import Time
from astropy import units
#- 19:00 UTC is noon Arizona
start = Time('2019-09-01T19:00:00')
end = Time('2019-10-01T19:00:00')
ephem = getCalAll(start, end, use_cache=False)
#- AZ local time of sunset
t = Time(ephem['MJDsunset'][0], format='mjd') - 7*units.hour
print(t.to_datetime(), 'vs', ephem['dirName'][0])
```
Which results in:
```
2019-09-02 18:50:34.175709 vs b'20190901'
```
Note: September 2 vs. September 1, i.e. the MJD of the sunset is being reported for the next day, not the current day.
I didn't fully discover why the original code didn't work, but this fix uses time conversions like …
> fix YEARMDD vs. MJD of sunset

- py/desisurvey/exposurecalc.py
- py/desisurvey/test/test_utils.py
- py/desisurvey/utils.py
The (Ra,Dec) to (Alt, Az) computation had a bug when the Az was in some quadrant.  Now fixed and also corrected the standard convention with Az = [0, 360[ .
> Fixed Az computation.

- py/desisurvey/ephemerides.py
- py/desisurvey/test/test_utils.py
This PR fixes unit tests that were failing at NERSC and on my laptop.  @dkirkby please check on your setup because this might be indicative of some delicate dependencies issue.  I verified that it is *not* astropy 1.2 vs. 1.3.
ephemerides.py L505 was failing with
```
======================================================================
ERROR: test_planning (desisurvey.test.test_surveyplan.TestSurveyPlan)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/global/common/edison/contrib/desi/code/desisurvey/master/py/desisurvey/test/test_surveyplan.py", line 35, in test_planning
ephem = Ephemerides(start, stop, use_cache=False, write_cache=False)
File "/global/common/edison/contrib/desi/code/desisurvey/master/py/desisurvey/ephemeri …
```
> fix desisurvey unit tests

- py/desisurvey/nextobservation.py
- py/desisurvey/plots.py
The changes in this PR make the results less wrong at the RA=0/360deg wraparound.  The gap where no observations are scheduled is mostly gone in the first pass of each program.
nextobservations.py: changed the condition on LST to use the utils.inLSTwindow() that checks for possible wraparound.
plots.py: amended the doc strings to specify that the basemap package has to be installed.
> Fixes one place where the ra=0/360 wraparound wasn't dealt with properly

- doc/changes.rst
- py/desisurvey/data/config.yaml
- py/desisurvey/optimize.py
Fixes indexing bug when using numpy 1.11 that was causing surveyplan to fail at NERSC.
Details: in older version of numpy, e.g. 1.11, indexing an array with a list of booleans behaved differently than with an array of booleans, e.g.
```
>>> import numpy as np
>>> x = np.arange(5)
>>> x[ [True, False, True, False, True] ]
__main__:1: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
array([1, 0, 1, 0, 1])
>>> x[ [1, 0, 1, 0, 1] ]
array([1, 0, 1, 0, 1])
>>> x[ np.array([True, False, True, False, True]) ]
array([0, 2, 4])
```
This is confusing and bad, and is fixed in recent versions of numpy so that lists of booleans are treated the same as arrays of booleans for indexing.
surveysim hit this problem when using `sel.flat` instead of `sel.flatten()`. …
> NERSC surveyplan

- py/desisurvey/test/test_progress.py
Hotfix for unit test failure under py 3.5 and astropy 1.x (I suspect that astropy 1.x is the cause, not py 3.5).
> Support either str/bytes column dtype

- py/desisurvey/progress.py
- py/desisurvey/test/test_progress.py
- py/desisurvey/utils.py
This PR modifies `desisurvey.progress.Progress.get_exposure()` such that:
* All table columns are upper-case.
* `NIGHT` is YYYYMMDD.
* `PROGRAM` is included.
* `EXPID` is included by default.
Please triple-check the logic for implementing `PROGRAM`.  I wasn't quite sure if `PROGRAM` is something that needs to be a per-tile attribute or a per-exposure attribute.
> Progress to exposure

- LICENSE.rst
- doc/changes.rst
- py/desisurvey/progress.py
- py/desisurvey/test/test_progress.py
This PR is a followup to #67, which hardcoded the tile pass -> program mapping since desimodel didn't provide that directly.  In the meantime, desihub/desimodel#67 adds `desimodel.footprint.pass2program` to do this based upon the desi-tiles.fits tile definition file.
This PR uses `desimodel.footprint.pass2program` if available (i.e. desimodel >= 0.9.1 is installed), and defaults to the previous hardcoded mapping since that is still valid for desimodel < 0.9.1.  If we never change the mapping, then this won't matter.  But if we do, now we just have to change the desimodel desi-tiles.fits file and the correct new mapping with automatically be used.
> use desimodel.footprint.pass2program if available

- doc/changes.rst
- py/desisurvey/progress.py
- py/desisurvey/test/test_progress.py
This PR sets the `EXTNAME` keyword on the table returned by `Progress.get_exposures()`.
> Add EXTNAME Keyword

- .travis.yml
- doc/changes.rst
- py/desisurvey/scripts/surveyinit.py
- py/desisurvey/scripts/surveymovie.py
The changes in this simple PR are to accommodate the SV Data Challenge.  
`surveyinit` currently assumes that the tile file includes a mixture of DARK, BRIGHT, and GRAY tiles, and crashed when I gave it a minimal tile file with just DARK tiles, and so I added a simple `if` statement to check.
The second change (to `surveymovie`) was to use uppercase column names when grabbing data from the `exposures.fits` file (which perhaps was standardized elsewhere / previously?).
> do not assume that input tile file includes all of DARK, BRIGHT, and GRAY tiles

- .travis.yml
- doc/changes.rst
- py/desisurvey/rules.py
- py/desisurvey/tileqa.py
Allows `PASS` in the `rules.yaml` file to be as large as 99 (previously only 0-7 were allowed).  This flexibility is needed to simulate SV/commissioning operations.
This should be a non-controversial, backwards-compatible change, so I'd like to self-merge once tests have passed.
> allow PASS to be 0-99

- py/desisurvey/data/config.yaml
desimodel.focalplane.get_tile_radius_deg() currently gives 1.6275 deg (0.9.10 master).  I think we'd rather err slightly on the high side than low side for these purposes.  My impression is that the change in primary mirror radius of curvature currently being discussed in commissioning will tweak this again, albeit only by a few arcseconds.
> Increase tile radius slightly

- py/desisurvey/NTS.py
- py/desisurvey/plan.py
- py/desisurvey/scheduler.py
- py/desisurvey/test/test_scheduler.py
- py/desisurvey/tiles.py
Adds Next Tile Selector functionality to the desisurvey scheduler.
The key addition of this routine to desisurvey is the NTS.py module that connects to the DOS NFS.py module to give the online system access to the desisurvey scheduler.
A few minor changes were made outside NTS.py:
- Planner and Scheduler save(...) methods were made atomic
- scheduler.next_tile(...) now accepts an program argument.  Tiles are selected from this program.
- next_tile also takes a skylevel argument, which is presently ignored.
- tiles.index(...) now accepts a default False return_mask argument.  If True, instead of raising an exception if an invalid tile ID is sent, the function returns a mask, indicating which IDs were valid.
> Add NFS/NTS interface to desisurvey scheduler

- .travis.yml
- bin/update_iers_frozen
- doc/changes.rst
- py/desisurvey/test/test_utils.py
- py/desisurvey/utils.py
This PR adds a workaround URL that `update_iers()`.  However, we also realized while testing this that `update_iers()` is intended to be run once at the start of the survey and then **NEVER AGAIN**.  For all other things that need IERS-A, `freeze_iers()` should be called first.
This means that any errors resulting from attempts to download IERS-A in other packages are caused by those packages failing to properly call `freeze_iers()`, *not* from an error in `desisurvey`.
In addition, the Travis test matrix has been updated, and a command-line script to call `update_iers()` is added.
The existing iers_frozen.ecsv file is a few years old, but let's not update that until we make a collective, documented decision.
> IERS workaround

- .travis.yml
- py/desisurvey/NTS.py
- py/desisurvey/data/config-cmx.yaml
- py/desisurvey/data/rules-cmx.yaml
- py/desisurvey/plan.py
- py/desisurvey/scheduler.py
- py/desisurvey/tiles.py
This PR lets NTS/desisurvey work with a commissioning tile file.  This requires some hacks around the default PROGRAMS; setting commissioning: True in the config.yaml file enables this behavior.  Commissioning tile files also don't get optimized HA assignments; commissioning tiles aim for HA = 0.
Extraneously, it also includes a maximum hour angle limit and a tweak to next_tile to allow it to go backwards in night_index (for instance, if someone requests a particular MJD that is earlier than a formerly requested MJD).
> Enable using NTS/desisurvey with CMX tile file; add HA limit.

- .travis.yml
- py/desisurvey/data/config.yaml
The new tile file changed the pass ordering.  This PR changes the config file to reflect that change.  It also removes the fiber_assignment_order constraints from the BGS/MWS surveys, since I do not believe they intend to impose such constraints.
> Change fiber_assignment_order to reflect new pass ordering

- py/desisurvey/NTS.py
- py/desisurvey/config.py
- py/desisurvey/data/config-cmx.yaml
- py/desisurvey/data/config.yaml
- py/desisurvey/data/rules-cmx.yaml
- py/desisurvey/data/rules-layers.yaml
- py/desisurvey/data/rules.yaml
- py/desisurvey/etc.py
- py/desisurvey/plan.py
- py/desisurvey/rules.py
- py/desisurvey/scheduler.py
- py/desisurvey/scripts/afternoon_plan.py
- py/desisurvey/scripts/collect_etc.py
- py/desisurvey/scripts/surveyinit.py
- py/desisurvey/scripts/surveymovie.py
- py/desisurvey/test/test_plan.py
- py/desisurvey/test/test_scheduler.py
- py/desisurvey/tiles.py
- py/desisurvey/utils.py
This PR and an associated one on surveysim reorganizes the desisurvey plan & scheduler state files into a single state file.  It also adds rudimentary afternoon planning code which scans for DESI spectra for ETC information and fiberassign directories for available tiles, but I will need to revisit the details of these bits once NERSC is back up.  Finally, it allows the derived available exposure & status files to no longer exactly match the tile file---i.e., if we have some weird commissioning TILEIDs, or if we change tile files, etc., that should not cause any issues.
There are also a few miscellaneous changes, like letting NTS be passed an "azrange" argument, which limits selected tiles to a particular azimuth range.
This PR does not make any changes to the actual survey simulations; …
> Migrate to single status file; rudimentary afternoon planning; allow tile & status files to not match.

- py/desisurvey/data/rules.yaml
- py/desisurvey/scripts/surveymovie.py
When we updated the tile file we changed the pass ordering of the passes and the pass <-> program mapping.  This doesn't matter for the "depth" rules, but it does for the default ~breadth first rules.  This PR attempts to update the default rules file to use the new pass ordering.
I'd appreciate it if someone else could inspect this for sanity.  I've just blindly tried to replace references to passes with the appropriate new numbers and verified that a surveysim run looks sane, but I don't follow the logic in this rules file well, so it was mostly a matter of symbol manipulation for me.
> Update default rules.yaml to use new tile file pass ordering.

- py/desisurvey/plots.py
This PR fixes interface bugs in `plot_sky_passes` in how it calls `desiutil.plots` functions:
* `desiutil.plots.init_sky` no longer accepts `ra_labels` and `dec_labels` options
* `desiutil.plots.plot_sky_circles` renamed argument `basemap` to `ax` (since it isn't a basemap anymore)
These changes are necessary for the survey-simulations tutorial to work.
I'll leave this open for a bit, but I'd like to get this merged tonight or tomorrow so that it can be included in the DESI data tutorials session on Friday morning.
> fix plot_sky_passes interface to desiutil.plots

- bin/surveyinit
- py/desisurvey/NTS.py
- py/desisurvey/optimize.py
- py/desisurvey/plan.py
- py/desisurvey/scheduler.py
- py/desisurvey/scripts/collect_etc.py
- py/desisurvey/scripts/surveyinit.py
- py/desisurvey/tileqa.py
- py/desisurvey/tiles.py
* optional increased verbosity when scheduler cannot schedule a tile
* only prepend FASURV to FAFLAVOR when FAFLAVOR does not already include the survey
* default to 0 HA in planning when no pre-planned LST is available
* add tileprogram to tiles object
* add routines to compute number of unique nights a tile was observed on in dark/gray/bright conditions, needed for SV completeness
* let LST optimization work for mixed programs making use of DARK/GRAY/BRIGHT time
* let LST optimization work when tiles need time in multiple kinds of conditions
* add feature to LST optimization removing tiles that have already been observed
* let tiles in LST optimization have different exposure lengths
* handle exptime = 0 correctly in LST optimization
* minor cleanups
> Enable NTS to handle SV tiles.

- doc/changes.rst
- py/desisurvey/etc.py
There was a small bug in the signal accumulation rate in the ETC.  This PR fixes that, replacing the signal accumulation rate with the square root of the weather factor, rather than the weather factor.  This PR also changes the transparency to be the square of the transparency in the weather factor.
In combination with a related PR on surveysim, this slightly improves survey margin.  That's a bit of a surprise, since the transparency fix makes things strictly worse, but the bug in the survey simulations more than compensates.
Original margin:
New margin:
The fix to the srate in the ETC looks like it should have a huge impact, but its effect was muted since it only effects how survey speed varies within an exposure; the bug didn't affect the initial expectations of how long an exposure …
> Fix transparency and seeing in exposure factor and ETC computations

- doc/changes.rst
- py/desisurvey/NTS.py
- py/desisurvey/data/config.yaml
- py/desisurvey/etc.py
- py/desisurvey/scheduler.py
- py/desisurvey/scripts/afternoon_plan.py
- py/desisurvey/scripts/collect_etc.py
- py/desisurvey/test/test_etc.py
- py/desisurvey/tiles.py
This PR moves sky computations into the ETC in preparation for a more detailed sky model.  Corresponding changes are necessary to desihub/desisurvey in order to work with this.
The present version only passes the current exposure time scalings for DARK/GRAY/BRIGHT into the sky, so that the survey sims are unchanged, despite the nominal times no longer being scaled by moon up factors.
This PR also implements a change where scheduler.next_tile looks for tiles whose hour angles will match the optimizations at the midpoints of the observations, rather than the beginnings of the observations.  This will make a difference ~now for operations on the mountain.
This will break the surveysim tests, since this and the corresponding surveysim PRs depend on one another.  I can't remember how we solve …
> Include sky in desisurvey.etc

- doc/changes.rst
- py/desisurvey/NTS.py
- py/desisurvey/data/config.yaml
- py/desisurvey/data/rules-depth.yaml
- py/desisurvey/data/rules-layers.yaml
- py/desisurvey/data/rules.yaml
- py/desisurvey/ephem.py
- py/desisurvey/etc.py
- py/desisurvey/forecast.py
- py/desisurvey/optimize.py
- py/desisurvey/plan.py
- py/desisurvey/rules.py
- py/desisurvey/scheduler.py
- py/desisurvey/scripts/afternoon_plan.py
- py/desisurvey/scripts/collect_etc.py
- py/desisurvey/scripts/run_plan.py
- py/desisurvey/scripts/surveyinit.py
- py/desisurvey/scripts/surveymovie.py
- py/desisurvey/svstats.py
- py/desisurvey/test/test_etc.py
- py/desisurvey/test/test_plan.py
- py/desisurvey/test/test_scheduler.py
- py/desisurvey/test/test_tiles.py
- py/desisurvey/tiles.py
This PR adds the option of calling gray time dark time, and treating the gray layer as just another dark layer.  The mechanism is to optionally in the surveyinit script add the gray time to the dark time and set the gray time to zero, and if that is set, merge the gray tile list with the dark tile list.  Then there is code in desisurvey.tiles to dynamically rename the gray tiles to dark tiles.
That's a little clunky, but I didn't want to go through the pain of changing desimodel's tiles at this point; we're going to have a new set of tiles soon anyway.
I also didn't want to remove the notion of 'gray' from the ephemerides option, since that presently controls the sky brightness, which it seems like should still exist.
There are a lot of knock on changes throughout the code base in places …
> Add option removing the gray layer

- doc/changes.rst
- py/desisurvey/NTS.py
- py/desisurvey/data/config.yaml
- py/desisurvey/etc.py
- py/desisurvey/optimize.py
- py/desisurvey/plan.py
- py/desisurvey/plots.py
- py/desisurvey/rules.py
- py/desisurvey/scheduler.py
- py/desisurvey/scripts/afternoon_plan.py
- py/desisurvey/scripts/collect_etc.py
- py/desisurvey/scripts/surveymovie.py
- py/desisurvey/tileqa.py
- py/desisurvey/tiles.py
* Allow program selection according to current survey speed, rather than ephemerides.  
* Make NTS more robust.  
* Set max dwell times based on not hitting airmass or observing dark tiles in twilight.  
* Allow requiring low pass tiles before overlapping high pass tiles, and preferring high pass tiles otherwise.
> Allow program selection according to current survey speed

- py/desisurvey/utils.py
This PR fixes #134.  @sbailey, could you please test in the candidate desiconda environment?
> Fix ERFA import error

- doc/changes.rst
- py/desisurvey/NTS.py
- py/desisurvey/plan.py
- py/desisurvey/scripts/afternoon_plan.py
This PR makes an initial implementation of a fiberassign holding pen.  Afternoon planning and the NTS looking for fiberassign files both in the holding pen and in the main fiberassign directory when deciding what tiles are available to observe.  If a given TILEID is only in the holding pen, and is requested during the night, it is copied into the main directory before the NTS returns it.
> Add fiberassign holding pen

- doc/changes.rst
- py/desisurvey/NTS.py
- py/desisurvey/holdingpen.py
- py/desisurvey/scripts/run_plan.py
Do not use legacy PM condition information for tile selection.  
Make it easier for ICS to move tiles into place from the holding pen.
Make nightly simulations use speed interface.
> Do not use legacy PM condition information for tile selection

- README.rst
- doc/Makefile
- doc/api.rst
- doc/changes.rst
- doc/conf.py
- py/desisurvey/NTS.py
This PR adds a few missing modules to api.rst. It also rearranges api.rst to make it easier to compare to the actual modules in the future.
> Add modules to api.rst

- bin/fba-main-onthefly.sh
Newer versions of modules do not allow modules to be swapped if they have prerequisites.  This prevents us from swapping in desired versions of desitarget and fiberassign unless we add the "-f" flag (force) to module swap.  This PR adds that flag.
> Add -f flag to module swap for new modules version compatibility.

- bin/fba-main-onthefly.sh
Permissions on fiberassign files designed on the fly at Kitt Peak were getting problematic permissions.  This forces those to be world readable and group writeable.  This is better done in fiberassign itself, but it can go in here for the moment.
> Force permissions on fa-on-the-fly files

- py/desisurvey/test/test_utils.py
- py/desisurvey/utils.py
This changes some references to astropy.coordinates.ICRS to astropy.coordinates.ICRS() to reflect some astropy API changes.
It also loosens the tolerance to 40" from 30" for the match to some precomputed transformations.  I don't understand why those transformations should have changed by 10", so maybe I should worry about this, but the old tolerance was 30" and the new tolerance is 40", so it's not obviously a big difference.
> Updates for astropy 6.

- doc/changes.rst
- py/desisurvey/forecast.py
This PR adds a keyword (default of `False` for backward-compatibility) that, if `True`, will return the plot object from `forecast_plots()`.
The justification is that, currently, the plot is displayed in _certain_ environments but not _all_ environments. Returning the object allows the plot to be saved (or manipulated in other ways).
> Allow plot object to be returned from forecast_plots()

- py/desisurvey/scripts/run_plan.py
This PR adds few updates on the `plan.png` plot which is attached to the wiki night plan:
- "done" tiles are now displayed as light gray
- "available" tiles are now displayed as solid green -- as we are getting closer to the end of the survey, it is this quantity that we would want to visualize; for instance, it allows one to easily see where is the region with remaining tiles
- a caption is added, with reporting the number of tiles for each case
- the x-axis is flipped, to follow the usual convention that R.A. increases towards left
Here s an example of the plan with the current main branch:
And here with this PR:
> planplot(): display udpates

- bin/fba-main-onthefly.sh
- py/desisurvey/scripts/surveymovie.py
This PR updates the desiconda, desitarget, desimeter, and fiberassign for the environment used by fiberassign on the fly.  A primary goal is to support the DESI extension; additionally, this addresses a lot of other changes that have occurred in the last several years.
An unrelated one-liner fixes a corner case in the survey movie creation.
> fiberassign-on-the-fly updates for extension

- bin/fba-main-onthefly.sh
This PR updates the DTCATVER value for the PROGRAM="BRIGHT1B" case.
@geordie666 : when DTCATVER=3.1.0 catalogs will be available, we will need to downloaded them to  kpno, and add the proper symlinks added to 1.1.1 catalogs.
> set DTCATVER for BRIGHT1B case

- bin/fba-main-onthefly.sh
- doc/changes.rst
This PR updates fiberassign on the fly to use `desitarget/4.0.0`. 
The update is necessitated by the bug-fix detailed in [desitarget issue #855](https://github.com/desihub/desitarget/issues/855) and [desitarget PR #856](https://github.com/desihub/desitarget/pull/856).
> Update fiberassign on the fly to use desitarget 4.0.0

- bin/fba-main-onthefly.sh
- doc/changes.rst
This PR updates fiberasssign-on-the-fly to use `desitarget/4.1.1` to keep pace with recent changes to the targeting code.
> Update fiberassign-on-the-fly to use version 4.1.1 of desitarget
